# Generated by Django 4.0.5 on 2022-06-19 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_post_options_remove_business_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialAmenities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('description', models.TextField(max_length=1000)),
                ('location', models.CharField(max_length=255)),
                ('neighborhood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenity', to='app.neighborhood')),
            ],
        ),
    ]
