# Generated by Django 4.0.5 on 2022-06-21 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_profile_neighborhood'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='neighborhood',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='neighborhood', to='app.neighborhood'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='neighborhood',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.neighborhood'),
        ),
    ]
